### ISSUE TITLE
Implement cost increase on configurable dates

### ISSUE THREAD

**Issue by ReneB** [evolution-events/Artaxerxes#2]
Allow administrators to set a certain date (X days before the event or just manual dates with a datepicker) and a cost increase for prizes for events.

**Comment by matthijskooijman** [comment]
We probably do not need this for Styx really (since we have a strict deadline), and maybe not entirely useful for other events either.

**Comment by matthijskooijman** [comment]
We could implement this as a RegistrationField that is either automatically or manually set for a registration when it is not paid on a given date yet.

This would have the advantage that:
 - RegistrationFields can already influence the registration's price
 - This is superflexible: For each event you can decide whether or not you need a raise by (not) defining such an option, you can even have multiple raises.

This probably needs some way to make such an option hidden (since you do not want it asked during registration or shown during or after registration, though you might want to show it once it gets set). To automatically set these options, you would need something like a `set_if_unpaid_after` option, though that is quite specific. Maybe doing this manually is more flexible anyway, also to handle corner cases, half-paid registrations, etc.

**Comment by matthijskooijman** [comment]
We're not really using the price increase mechanism anymore, so I'm going to close this. We can always reconsider if it comes up again.
