### ISSUE TITLE
How to handle medical data (perhaps not in Artaxerxes?)

### ISSUE THREAD

**Issue by BrendaH** [evolution-events/Artaxerxes#42]
Instead of saving all medical data that someone is willing to share into our system (only when person is also registered for an event), we could do the following:

Only ask for food allergies that our cooks should take into account.
Present people with a pdf file that they can print and fill in at home for all their medical issues that might be relevant in case of emergency (first aid / ambulance). This file will be asked for at check in. If someone forgot to bring it we have copies to fill in at incheck. (but we want to give people the opportunity to prepare this)
This file will be put away without looking at it and will only be brought out when an actual emergency occurs where the person him/herself can no longer give information.
The file will be destroyed (burned or ripped to tiny pieces) at the end of the event. Or, if a checkout is available, handed back to the person to do with as he/she pleases.

**Comment by matthijskooijman** [comment]
Some thoughts:
 - Currently we pass on a selection of medical details to the first aiders in advance. Is this still useful? I'm currently the one to decide what to (not) pass on, but that's not always easy to decide (not having a first aid degree myself).
 - Above an approach is suggested that basically means we will ask for medical details, but only look at them in a significant emergency. Above is one implementation, we could also ask for details online, but take some technical and organisational measures to make sure these are not looked at until needed.
 - In some cases, it might be useful for the organizers or emergency coordinator to know some info beforehand (epilepsy - no strobe lighting, smoke allergy, psychic problems).
 - In some cases, participants might not realize what information is relevant to what parties. Should we have a generic "this might be relevant, you decide" entry?

**Comment by matthijskooijman** [comment]
In the implementation as of now, we're asking for two bits of information:
 - Food allergies, to be shared with the kitchen crew
 - Other relevant information, to be shared with the event organisers.

This seems a fairly open-ended question, putting the responsibility for deciding what is relevant and what is not with the participant. We have to ask for this info in advance, since it might contain things that influence the game design and preparations.

In this model, there is no explicit provision for information to be communicated to ambulance personnel or first-aiders, but if a participant has important information that should be communicated, they can explicitly specify so in the second field of course. However, since such information is *not* needed to be known in advance and not needed to be known by all the crew, it might be better to not ask for it until at the event (either by letting participants hand in a hardcopy, or asking them to talk to the safety coordinator in person).

So for now, just these two questions (in addition to emergency contacts, of course) should be sufficient for now.

@BrendaH, @ReneB, Agreed?

**Comment by ReneB** [comment]
"Kind of." I feel that realistically, asking for such info at the event in the form of talking to a safety coordinator may not always work: 
- for one, because people are people and inherently fallible, forgetting to mention their fatal allergy to bad plots or being late to the event and missing the time-in talk
- second, because stress happens at these events and everything that's designed to happen last minute has a very real chance of falling by the wayside (especially if said people come in late as well). 

Asking for a hardcopy might work better, but of course _only_ if we promise to shred and burn them afterwards.

Aside from that, if there is space or a way to do so, we should communicate some proper examples of what they can put in the second field, just to make sure we're on the same page about what we expect there, and include the provision that they're also free to tell us later on through a hardcopy form at the event.

**Comment by matthijskooijman** [comment]
> Asking for a hardcopy might work better, but of course only if we promise to shred and burn them afterwards.

Agreed, but this is still something that can be done out-of-band (e.g. in briefings rather than the registration system).

> Aside from that, if there is space or a way to do so, we should communicate some proper examples of what they can put in the second field, just to make sure we're on the same page about what we expect there, and include the provision that they're also free to tell us later on through a hardcopy form at the event.

Yeah, there already are some examples:

![image](https://user-images.githubusercontent.com/194491/69166636-d8de4f00-0af3-11ea-891b-0361a420a487.png)

They might need to be improved, but that would be part of #64.

**Comment by ReneB** [comment]
🆒

**Comment by ReneB** [comment]
The idea at this point is that we don't separately request info to provide to medical professionals. If and when a medical professional needs to look at, for example, an unconscious player, we would just provide that person's medical info to the professional. For First Aiders, the emergency coordinator will, before the event, read the information and discuss with the participant whether or not to provide the information to the First Aiders.

We should add this information, like "this information will be read by our emergency team and, when required, be shared with any medical personnel" to the form. This is all we need to do before first registrations.

**Comment by matthijskooijman** [comment]
I've put the needed clarification in #64, so we can remove this issue from MVP (and leave it open for future review, I think).

**Comment by BrendaH** [comment]
> We should add this information, like "this information will be read by our emergency team and, when required, be shared with any medical personnel" to the form. This is all we need to do before first registrations.

With the current field 'take into account for event' this remark does not make much sense. We're explicitly (in the help text and label of the field) asking for stuff to take into account while organizing. 
Also, it may very well be read by the whole organisation.

The page with this field already suggests to read the privacy policy, should we then also add more 'noise' to the page with this extra statement that's a bit off?

**Comment by ReneB** [comment]
No, I don't think we should. This suggestion was made, I think, before completely thinking through the whole data management strategy in terms of the GDPR statement.

**Comment by matthijskooijman** [comment]
We have a working implementation for this now, so I'm closing this.
