### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by BrendaH** [evolution-events/Artaxerxes#5]
Users should be able to login and see stuff that's 'theirs' and make registrations for themselves.

**Comment by ReneB** [comment]
Do some research on what kind of authentication / registration modules Django provides and/or allows, keeping in mind the following things:

- [ ] We need confirmation that the e-mail address used is owned by the one who's registering their account in the system.
- [ ] A "social" login would be better than using our own forum as the basis.
- [ ] Users need to "opt in" to us storing some data beyond the event itself (to simplify and/or speed up registrations).
- [ ] Users would probably need to "opt in" to us storing their mail addresses and keeping them posted about future events.
- [ ] We may want to be our own ID Provider as well. That could be done by anything from encrypted cookies with a shared secret between apps to full-blown OpenID implementation. Matthijs also suggested file-based sessions but let's pretend I didn't hear that.

**Comment by matthijskooijman** [comment]
Some privacy/GDPR/AVG-related observations.

 - Most data we store will be personal data, while medical data will be special personal data.
 - Storing personal data is only allowed based on a ground specified in [article 6](https://gdpr-info.eu/art-6-gdpr/). For special personal data, additionally one of the grounds in [article 9](https://gdpr-info.eu/art-9-gdpr/) is needed.
 - Data we store related to an event subscription, would be related to a contract we have (or intend to have) with the participant, so is lawful under 6.1.b.
 - Storing an e-mail address serves to send people mailings, and can be lawful under 6.1.a (explicit consent) or 6.1.f (because it serves the legitimate interests of the receiver). When someone unsubscribes from all mailing lists, it would still be relevant to store the e-mail address to allow account recovery.
 - Storing other data between events (e.g. address data) would be lawful under 6.1.a (explicit consent), since we already plan to make that opt-in and easy to opt-out. This is less likely to be lawful under 6.1.f since the interests of "easier to register at future events" might not weigh up to the privacy risk of storing this data.
 - Storing medical data would be lawful under 6.1a and 9.2.a (both explicit consent). 9.2.a is only allowed for "specified purposes", so we must be explicit about what we use this data for. It seems this article does not specify any particular constraints on *how long* to store this data, but it is likely that "for a future event" does not count as "specified".
 - [Article 17](https://gdpr-info.eu/art-17-gdpr/) specifies the right to be forgotten, which is possible on a number of grounds. Most likely ground would be that data is "no longer necessary in relation to the purposes for which they were collected or otherwise processed" (17.1a). We can probably argue that at least keeping a user object with a name is necessary for the purpose of history-keeping, but all other data (including e-mailaddress, username, etc.) should probably be removed. For data where the only ground is consent (6.1a), this consent can always be removed and the data must be deleted (even if it would still be necessary! 17.1b). For data whose only ground is 6.1f (legitimate interests), there is an explicit right to object ([article 21](https://gdpr-info.eu/art-21-gdpr/) and 17.1.c). There are some other grounds, which likely won't apply to us.

**Comment by matthijskooijman** [comment]
If we need single-sign-on for other applications, we can let them authenticate against Arta. We might use openid (which, I think, always requires explicit consent of the user to forward the authentication) or perhaps the CAS protocol (which, I think can work transparently).

CAS is described at https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html and seems fairly simple (authentication redirects to the CAS server, which forwards back to the application, passing a token. The application makes a server-to-server connection to exchange the token for the user data which is used to build the application user session.

https://github.com/jbittel/django-mama-cas has a Django CAS server. It seems there are some client implementations for phpbb.

**Comment by matthijskooijman** [comment]
I moved the GDPR-related stuff to a new ticket #43.

**Comment by matthijskooijman** [comment]
Master now has django-alluser enabled, which handles social logins, user creation, multiple e-mail address management and verification, etc.

This still needs to be customized and styled. It seems [the recommended way](https://github.com/pennersr/django-allauth/issues/678#issuecomment-50183064) is to copy the various allauth templates and apply our own CSS, though [using at least the login/logout templates as-is](https://github.com/pennersr/django-allauth/issues/678#issuecomment-248517375) is probably also possible. For the other templates (email, social account and password management), we probably want to integrate them into a account settings interface somehow, which is probaly easiest when copying the templates and adapting them to our needs.

There is also an example project in the allusers repository that [has a few sets of example templates](https://github.com/pennersr/django-allauth/tree/master/example/example/templates) (such as for bootstrap) that might be good as a basis.

**Comment by matthijskooijman** [comment]
Basic authentication works, so I'm closing this issue. See #53 about the remaining account management stuff mentioned in the previous comment.
