### ISSUE TITLE
Let users manage their account

### ISSUE THREAD

**Issue by matthijskooijman** [evolution-events/Artaxerxes#53]
This is about managing things like associated e-mailaddresses, password, social accounts, not about their registration data.

**Comment by ReneB** [comment]
I think we should determine which parts of this are "no regret moves" - as in, once we implement them, we can't go back without a whole lot of hassle - and which can be left open for the future.

Then, we should figure out which of these features can be postponed. And the only things we need to really worry about are the "no regret moves" that cannot be postponed.

Is django-alluser easy to any of you? Because then you may be able to make a decent start with this, and/or at least figure out what MVP needs.
