### ISSUE TITLE
Define registration options and their structure

### ISSUE THREAD

**Issue by BrendaH** [evolution-events/Artaxerxes#9]
Options like 'stays until Monday', 'helps build up' and other stuff that might influence the price. Where can those be defined, how are they presented to the user, how are they stored, etc.?

**Comment by ReneB** [comment]
I think "slot types" (things like NPC/Player) can be treated differently than options like "stays until Monday" or, as a recent example, "would like some alcohol please"

**Comment by matthijskooijman** [comment]
See #3

**Comment by matthijskooijman** [comment]
For On The Styx, we have a new usecase: Options might be orthogonal, rather than subtypes/suboptions. E.g. users can register as either "Live in NL" or "Live abroad", and select between "Male" / "Female" / "Either". Here, the second is not a subtype of either of the first, but both apply orthogonally.

OTOH, both are in a way subtypes of "Player", since anyone registering as "Crew" should not get, these options (and more importantly, should not take up a slot for any of these options). In general, I suspect that making options (and/or individual choices within an option) dependent on other choices is a sufficiently generic approach (one step further would be to say "Allow this option when choice A but not choice B is made", or other more complex boolean expressions, but I suspect this is not needed in practice).


One important implication of registration options is the number of spots available. In general, I guess each *choice* has an (optional) limited number of places available, where a registration takes up one place off each choice that is associated with that registration. More complicated setups (such as two choices sharing a single number of spots) can also be imagined, but in practice I think this could be implemented by two dependent options instead (e.g. if you want to allocate 8 spots to either "Stay until monday" or "Stay until tuesday", you could introduce a "Stay longer option" with 8 spots, and let "Until monday" and "until tuesday" depend on that).

One other implication of limited spots is that when the spots are filled, registrations will end up on the waiting list. This suggests multiple waiting lists, one for each choice with limited spots, since when a place frees up, not all registrations will qualify. In practice, a single waiting list is probably sufficient, and it is up to the organiser to filter the list and find the first qualifying registration when a spot is freed.

One caveat is that when a spot frees up (e.g. a participant cancels), this immediately allows a new registration to take up the spot, even when there are still people on the waiting list (that might need to confirm that they are still interested before they can be admitted, so admitting them before cancelling the old registration is not always an option). The current system solves this by checking whether there is any registration on the waiting list for a particular option, and if so, redirect all new registrations for that option to the waiting list as well. This works well when there is only a single option, but once a registration has multiple options (e.g. on the styx international run), this breaks (since when a registration is on the waiting list because e.g. the international places are full, this will also cause e.g. all new female god registrations to be also put on the waiting list even when there are still places free.

Iow, from a registration on the waiting list, it is not clear what options it was waiting upon. This could be solved by explicitly storing what options a registration waits on, though that would also involve expanding that list when other options fill up later (and notably not *clearing* this waiting on status when places free up). Alternatively, each choice with limited spots could keep an explicit "full" flag, that is automatically set when the number of spots frees up, and only cleared manually (or automatically when there are no waiting list registrations with that choice anymore).

**Comment by matthijskooijman** [comment]
Assume there are two options, M/F and NL/INTL. Each choice has exactly 2 spots.

Then, if registrations are
> M+NL, M+NL, M+NL (Waiting) 
and one cancels, you get
> M+NL, M+NL (Waiting)
and new registrations using either M or NL should be blocked (since they would prevent the waiting list registration from being admitted).

If registrations are
> M+NL, M+INTL, F+INTL, M+INTL (Waiting)
Then F+NL can still register directly. If F+INTL cancels and you get:
> M+NL, M+INTL, M+INTL (Waiting)
Then F+NL can still register, but all others would need to wait since they would block the waiting registration).

If registrations are
> F+NL, M+NL, M+INTL, F+INTL, M+INTL (Waiting)
Then no new registrations can be made directly. When F+NL cancels:
> M+NL, M+INTL, F+INTL, M+INTL (Waiting)
Then F+NL can directly register again, since that would not block the waiting registration.

If registrations are
> F+NL, M+NL, M+NL(Waiting)
Then F+INTL should be allowed directly. F+NL/M+NL should end up on the waiting list (since NL is full). M+INTL should probably be allowed directly, even though it would block the waiting list registration.

The first examples suggest a policy of "If a new registration would block a registration on the WL, put it on the WL" (iow, if it shares a choice with any WL registration), but this does not work for the last example. Amending it to only consider registrations on the WL all of whose choices are not currently full (i.e. if this registration was made *now*, it would not necessarily end up on the waiting list) would work for this case, but can also get complicated quickly.

Additionally, I can imagine a case where registrations are:
> F+NL, M+NL, M+INTL, F+INTL, M+INTL (Waiting)
Then F+INTL cancels:
> F+NL, M+NL, M+INTL, M+INTL (Waiting)
Now, you could say that F+INTL can directly register again, because it though it would block M+INTL, M+INTL is already blocked by M being full. However, in practice, in a case like this, you might want to ask the M+INTL on the waiting list if they would want to change to F+INTL and attend the event, without that spot being taken up.

A slight variation on this is:
> F+NL, M+NL, M+INTL, M+INTL (Waiting)
Then F+NL cancels:
> M+NL, M+INTL, M+INTL (Waiting)
Now, F+NL can directly register again (since it does not block the WL registration in any way). Again except if you would want to allow the WL registration to change to F+INTL to fill up the spot.
Also note that F+INTL would have been able to register directly before the cancellation, so it makes sense that they can do that after the cancellation too, even if that would block the M+INTL changed F+INTL from the waiting list.
Actually, looking at this, it seems that before the cancellation the M+INTL could have changed to F+INTL to get off the waiting list, so I guess this should not be treated specially after cancellation either.
So, before F+INTL can register, and afterwards F+INTL and F+NL can register.

A policy where each choice has an explicit "full" flag seems to work for all cases. I think it would be useful to set the full flag as soon as the choice fills up (even when there are no waiting list registrations), since then it is also set when a choice fills up after a registration using it is already on the waiting list (because another choice for that registration was full earlier).

Then it also seems acceptable to auto-clear a full flag for all choices of a cancelled registration (i.e. when there again slots free for a choice) *and* no waiting list registrations are using that option.

Note that it appears that such a full flag with autoclear effectively means that the full flag can be replaced by a check that says "if the options are full *or* the option appears on the waiting list", but this is not true for options that do appear on the waiting list but have never been full yet (e.g. M+INTL is on the WL because INTL is full, but M is not yet full).

Conclusion: A full flag with autoclear should work well.

**Comment by matthijskooijman** [comment]
Assume there are two options, M/F and NL/INTL. Each choice has exactly 2 spots.

Then, if registrations are
> M+NL, M+NL, M+NL (Waiting) 

and one cancels, you get

> M+NL, M+NL (Waiting)

and new registrations using either M or NL should be blocked (since they would prevent the waiting list registration from being admitted).

If registrations are

> M+NL, M+INTL, F+INTL, M+INTL (Waiting)

Then F+NL can still register directly. If F+INTL cancels and you get:

> M+NL, M+INTL, M+INTL (Waiting)

Then F+NL can still register, but all others would need to wait since they would block the waiting registration).

If registrations are

> F+NL, M+NL, M+INTL, F+INTL, M+INTL (Waiting)

Then no new registrations can be made directly. When F+NL cancels:

> M+NL, M+INTL, F+INTL, M+INTL (Waiting)

Then F+NL can directly register again, since that would not block the waiting registration.

If registrations are

> F+NL, M+NL, M+NL(Waiting)

Then F+INTL should be allowed directly. F+NL/M+NL should end up on the waiting list (since NL is full). M+INTL should probably be allowed directly, even though it would block the waiting list registration.

The first examples suggest a policy of "If a new registration would block a registration on the WL, put it on the WL" (iow, if it shares a choice with any WL registration), but this does not work for the last example. Amending it to only consider registrations on the WL all of whose choices are not currently full (i.e. if this registration was made *now*, it would not necessarily end up on the waiting list) would work for this case, but can also get complicated quickly.

Additionally, I can imagine a case where registrations are:

> F+NL, M+NL, M+INTL, F+INTL, M+INTL (Waiting)

Then F+INTL cancels:

> F+NL, M+NL, M+INTL, M+INTL (Waiting)

Now, you could say that F+INTL can directly register again, because it though it would block M+INTL, M+INTL is already blocked by M being full. However, in practice, in a case like this, you might want to ask the M+INTL on the waiting list if they would want to change to F+INTL and attend the event, without that spot being taken up.

A slight variation on this is:

> F+NL, M+NL, M+INTL, M+INTL (Waiting)

Then F+NL cancels:

> M+NL, M+INTL, M+INTL (Waiting)

Now, F+NL can directly register again (since it does not block the WL registration in any way). Again except if you would want to allow the WL registration to change to F+INTL to fill up the spot.
Also note that F+INTL would have been able to register directly before the cancellation, so it makes sense that they can do that after the cancellation too, even if that would block the M+INTL changed F+INTL from the waiting list.
Actually, looking at this, it seems that before the cancellation the M+INTL could have changed to F+INTL to get off the waiting list, so I guess this should not be treated specially after cancellation either.
So, before F+INTL can register, and afterwards F+INTL and F+NL can register.

A policy where each choice has an explicit "full" flag seems to work for all cases. I think it would be useful to set the full flag as soon as the choice fills up (even when there are no waiting list registrations), since then it is also set when a choice fills up after a registration using it is already on the waiting list (because another choice for that registration was full earlier).

Then it also seems acceptable to auto-clear a full flag for all choices of a cancelled registration (i.e. when there again slots free for a choice) *and* no waiting list registrations are using that option.

Note that it appears that such a full flag with autoclear effectively means that the full flag can be replaced by a check that says "if the options are full *or* the option appears on the waiting list", but this is not true for options that do appear on the waiting list but have never been full yet (e.g. M+INTL is on the WL because INTL is full, but M is not yet full).

Conclusion: A full flag with autoclear should work well.

**Comment by matthijskooijman** [comment]
Jumping back to the registration options themselves, here's how things would look for some of our past events.

*Styx*

 - Option: Registration type
    - Choice: Crew
 	   - Slots: 5
       - InviteOnly: <list of users>
       - Price: €x
    - Choice: Player
       - Slots: 16
       - Maybe slots are not needed, since Dutch+International is already 16, but it might be useful for feedback to show that player slots are full.
       - Price: €x
 - Option: Small Purse
	- Boolean option
    - Extra cost: €-x
    - InviteOnly: <empty list of users>
 - Option: Nationality
    - Depends on type=Player
    - Choice: Dutch
       - Slots: 8
    - Choice: International
       - Slots 8
 - Option: Character Gender
    - Depends on type=Player
    - Choice: Male
       - Slots: 8
    - Choice: Female
       - Slots 8
    - Don't care
       - This needs no slots, since the total player registrations are limited to 16 (so male+female+don't care cannot end up at more than 16)
 - Option: Alcohol package
    - Boolean option
    - Extra cost: €xx
    - Change until: 2019-xx-xx
 - Option: Stay extra nights
    - Change until: 2019-xx-xx
    - Choice: monday-night
       - Extra cost: €xx
    - Choice: tuesday-night
       - Extra cost: €xx
    - etc.

Here, I've added an `InviteOnly` property for crew. That could point to a group of users, or maybe it could be a boolean option and you could generate a special link with a token that unlocks an invite-only option. The latter could also be interesting to invite crew that are not registered in the system yet (but I guess that having a list of users is something we want in any case).

This lists both "Price" and "Extra cost" options. I think these would probably be treated pretty much the same (just sum them), except that they might be rendered differently (e.g. Player (€50) and "Tuesday night (+€10)"), but maybe just using Price everywhere is also just fine.

I've included a boolean option, which could also be an option with two choices (which could make things simpler because then things like Price only need to apply Choices, not Options).

Small Purse spots are now included as an invite-only option (to prevent users from selecting it) that can be selected afterwards by the admins manually after the normal procedure of requesting a small purse spot by e-mail and doing the lottery for assigning them. These spots need to be reflected in the system to adjust the total registration price.

Alternatively, we could also include this as a user-selectable option, so a player can indicate they want a small-purse spot by selecting it rather than sending us an e-mail. Initially the option would have unlimited slots (to allow a lottery), after the lottery a number of slots could be assigned.

Options that have only one choice (e.g. type when not invited as crew) should probably be rendered as labels instead of choices (or maybe not at all?).

Change until options can be changed by the participant themselves online, until the date given.

*Zomerkamp*

 - Option: Registration type
    - Choice: Crew
 	   - Slots: xx
       - InviteOnly: <list of users>
       - Price: €x
    - Choice: Player
       - Slots: xx
       - Price: €x
 - Option: Small Purse
    - Depends on type=Player
	- Boolean option
    - Extra cost: €-x
    - Slots: 0
 -  Option: Sponsor small purse tickets
    - Change until: 2019-xx-xx
    - Depends on type=Player
    - Choice: No
    - Choice: €10
       - Price: €10
    - Choice: €20
       - Price: €20
    - etc...

For small purse, this initially has 0 spots, which can be manually made available once sponsortickets are sold.

**Comment by matthijskooijman** [comment]
So far, I've used Option to indicate things that need a value and Choice for the possible values. In common practice, this might be reversed (e.g. you pick something from multiple options), though you can also say that you have multiple choices for a question. Technically, a choice is something you make, rather than something that you assign to a registration perhaps?

Maybe a more generic "RegistrationField" that has a number of "RegistrationFieldOptions" is better (and a "RegistrationFieldValue" for an actual registration)?

**Comment by matthijskooijman** [comment]
I have a basic implementation of this data model, with Django admin site support and test data as shown for Styx above. So far so good. Next step is cleaning that up and committing it, then see if we can use this data to generate the actual registration form. This probably needs dynamically generating a form object, which seems to be possible in Django. Here's something similar for inspiration: https://github.com/MarkusH/django-dynamic-forms/blob/master/dynamic_forms/models.py#L104

**Comment by matthijskooijman** [comment]
This is now implemented, so I'm closing this. There are some loose ends, which I moved to #67, #70 and #71.
